import { jsPDF } from 'jspdf';

interface ParsedSection {
    title: string;
    items: string[];
}

interface ParsedBriefing {
    briefingTitle: string;
    sections: ParsedSection[];
}

// Helper to strip emojis and unsupported unicode characters which break jsPDF standard fonts.
const stripEmojis = (str: string): string => {
    return str.replace(/([\u2700-\u27BF]|[\uE000-\uF8FF]|\uD83C[\uDC00-\uDFFF]|\uD83D[\uDC00-\uDFFF]|[\u2011-\u26FF]|\uD83E[\uDD10-\uDDFF])/g, '')
              .replace(/\s+/g, ' ').trim();
};

export const exportBriefingToPdf = async (briefing: ParsedBriefing): Promise<void> => {
    try {
        const doc = new jsPDF({ orientation: 'p', unit: 'pt', format: 'a4' });

        const pageW = doc.internal.pageSize.getWidth();
        const pageH = doc.internal.pageSize.getHeight();
        const margin = 40;
        const maxW = pageW - margin * 2;
        let y = margin;
        
        // --- Footer Function ---
        const addAuditFooter = (pageNumber: number) => {
            doc.setFont('courier', 'normal');
            doc.setFontSize(8);
            doc.setTextColor(100, 116, 139); // Slate-500
            
            const timestamp = new Date().toISOString().replace('T', ' ').substring(0, 19);
            const footerLine1 = `GENERATED BY MEDIBRIEF C.I.L. v3.0 | TIMESTAMP: ${timestamp} UTC`;
            const footerLine2 = `WARNING: AI-ASSISTED DRAFT. CLINICAL VERIFICATION REQUIRED BEFORE EHR ENTRY.`;
            
            doc.text(footerLine1, margin, pageH - 25);
            doc.setTextColor(220, 38, 38); // Red-600 for warning
            doc.text(footerLine2, margin, pageH - 15);
            
            doc.setTextColor(150);
            doc.text(`Page ${pageNumber}`, pageW - margin - 30, pageH - 15);
            
            // Reset text color for body
            doc.setTextColor(0);
        };

        const checkPageBreak = (requiredHeight: number) => {
            if (y + requiredHeight > pageH - 50) { // Leave space for footer
                addAuditFooter(doc.getCurrentPageInfo().pageNumber);
                doc.addPage();
                y = margin;
                return true;
            }
            return false;
        };

        // Title
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(18);
        doc.text(stripEmojis(briefing.briefingTitle), pageW / 2, y, { align: 'center' });
        y += 40;

        // Sections
        for (const section of briefing.sections) {
            if (!section.items || section.items.length === 0) continue;

            checkPageBreak(40);
            
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(14);
            doc.setTextColor(30, 41, 59); // Slate-800
            doc.text(stripEmojis(section.title), margin, y);
            y += 20;

            doc.setFont('helvetica', 'normal');
            doc.setFontSize(10);
            doc.setTextColor(51, 65, 85); // Slate-700
            
            for (const item of section.items) {
                const lines = doc.splitTextToSize(`• ${stripEmojis(item)}`, maxW - 15);
                const requiredHeight = lines.length * 12;

                if (checkPageBreak(requiredHeight)) {
                    doc.setFont('helvetica', 'bold');
                    doc.setFontSize(12);
                    doc.text(`${stripEmojis(section.title)} (continued)`, margin, y);
                    y += 20;
                    doc.setFont('helvetica', 'normal');
                    doc.setFontSize(10);
                }
                
                doc.text(lines, margin + 15, y);
                y += requiredHeight + 4;
            }
            y += 20;
        }
        
        // Add footer to last page
        addAuditFooter(doc.getCurrentPageInfo().pageNumber);
        
        // FIX: Windows does not allow colons in filenames. Replace : with -
        const safeTimestamp = new Date().toISOString().replace(/:/g, '-').split('.')[0];
        doc.save(`MediBrief-Shift-Briefing-${safeTimestamp}.pdf`);

    } catch (error) {
        console.error("Error exporting PDF:", error);
        throw new Error("Failed to generate PDF document.");
    }
};