export type AuditEventType =
    | 'SYSTEM_INIT'
    | 'PATIENT_ACCESS'
    | 'ALERT_TRIGGERED'
    | 'ALERT_DISMISSED'
    | 'ALERT_ACTION'
    | 'DOSAGE_CHECK'
    | 'BRIEFING_GENERATED'
    | 'EXPORT_PDF'
    | 'CLINICAL_CANDIDATE_CONFIRMED'
    | 'CLINICAL_CANDIDATE_REJECTED'
    | 'CLINICAL_RESOURCE_CREATED'
    | 'CLINICAL_RESOURCE_AMENDED'
    | 'CLINICAL_RESOURCE_MARKED_ERROR'
    | 'CLINICAL_SOURCE_VIEWED'
    | 'CLINICAL_OBSERVATIONS_CONFIRMED'
    | 'APPOINTMENT_PROPOSAL_CREATED'
    | 'CLINICAL_NOTE_SAVED'
    | 'ADVISORY_ACKNOWLEDGED'
    | 'ADVISORY_TASK_CREATED'
    | 'MEDICATION_LABEL_REVIEW'
    | 'PATIENT_SUMMARY_EXPORTED'
    | 'DOCUMENT_EXTRACTION_STARTED'
    | 'DOCUMENT_EXTRACTION_COMPLETED'
    | 'DOCUMENT_EXTRACTION_FAILED'
    | 'DIAGNOSTIC_REPORT_REVIEW_STARTED'
    | 'DIAGNOSTIC_REPORT_REVIEW_CONFIRMED'
    | 'DIAGNOSTIC_REPORT_REVIEW_CANCELLED'
    | 'DIAGNOSTIC_REPORT_CONFLICT_RESOLVED'
    | 'DIAGNOSTIC_REPORT_DUPLICATE_SKIPPED'
    | 'DETERMINISTIC_SUMMARY_GENERATED'
    | 'GROUNDING_BUNDLE_GENERATED'
    | 'GROUNDED_ASSISTANT_COMPLETED'
    | 'GROUNDED_ASSISTANT_REJECTED'
    | 'MEDICATION_RECONCILIATION_REVIEWED'
    | 'MEDICATION_RECONCILIATION_TASK_CREATED'
    | 'TREND_SUMMARY_GENERATED'
    | 'TREND_GROUNDING_BUNDLE_GENERATED'
    | 'TREND_ASSISTANT_COMPLETED'
    | 'TREND_ASSISTANT_REJECTED'
    | 'REMINDER_TASK_CREATED';

export type AuditActor = 'AI' | 'USER' | 'SYSTEM';

export interface AuditEvent {
    id: string;
    timestamp: number;
    type: AuditEventType;
    patientId: string;
    actor: AuditActor;
    details: string;
    metadata?: Record<string, any>;
}
